#!/bin/sh
#Program written for EOPSY course at WUT to modify a file name
#Author: Jakub Szumski

PROGNAME="$(basename "$0")"

recursion=0
upper=0
lower=0
sed_flag=0
sed_pattern=none


#validation part

validate_flags() {
	
	if test  $upper -eq 1 -a $lower -eq 1;
	then
	  echo "Lower and upper chosen!!!"
	  usage >&2
	  exit 1
	fi

}

validate_sed () {

	if test $upper -eq 0 -a $lower -eq 0 -a  $sed_pattern = "none";
	then
	  echo "Sed pattern cannot be none!!"
	  usage >&2
	  exit 1
	fi

	#if sed response is not valid then fail

}

#recursive function
recursive() {

cd $1
for el in *;
do	
	#dir_name="$(basename $el)"
	
	if test "$sed_pattern" != "none";
	then
	  newname=$(echo "$el" | sed "$sed_pattern")
	fi

	if test  $upper -eq 1;
	then
	  newname="$(echo "$el" | tr a-z A-Z)"
	fi

	if test  $lower -eq 1;
	then
	  newname="$(echo "$el" | tr A-Z a-z)"
	fi
	
	if test "$el" != "$newname";
	then
	  mv "$el" "$newname"
	fi
	
	if test -z "$(ls -A "$newname")";
	then
	  continue
	fi

	if test -d "$newname";
	then
	  recursive $newname
	fi


done

cd ..
}


#usage information

usage () {
cat <<- _EOF_

$PROGNAME is a scirpt that modifies the filename with either lowercasting or uppercasting it with optionall calling the sed pattern

usage:

	$PROGNAME [-r] [-l|-u] <dir/filenames....
	$PROGNAME [-r] <sed pattern> <dir/filenames...>
	$PROGNAME [-h] 

options:

	-l 		lowercase
	-u 		uppercase 
	-h 		show usage
	<sed pattern>	pattern to which we should modify filenames

	!!!!lowercase and uppercase cannot be used at once!!!

$PROGNAME correct examples:

	$PROGNAME -u some_file handbook.txt
	$PROGNAME -l my_directory
	$PROGNAME -r -u my_handbook
	$PROGNAME 's/A/c/' wordlist.py phonebook.txt

$PROGNAME incorrect examples:
	
	$PROGNAME -a
	$PROGNAME -u -l file
	$PROGNAME -r <sed pattern>



_EOF_
return

}

#Main part of the script

if test -z "$1" -o "$1" = "-h";
then
  usage 
  exit 0
fi

while [ -n "$1" ]; do
  case "$1" in
	-r)	recursion=1	
		;;
	-l) 	lower=1
		sed_flag=1
		;;
	-u) 	upper=1
		sed_flag=1
		;;
	-*) 	echo "Option unavaliable"
		usage >&2
	       	exit 1
		;;
	*)	if test $sed_flag -eq 0; 
		then
		  sed_flag=1
		  sed_pattern=$1
		else	
		  break
		fi
		;;
  esac
  shift
done


validate_flags

validate_sed

if [ -z "$1" ];
then
  echo "No file/path was given"
  exit 1
fi

#execution of program

for el in "$@"; do

	if test ! -e $el;
	then
	  echo "Incorrect file name"
	  continue
	fi

	if test "$sed_pattern" != "none";
	then
	  newname=$(echo "$el" | sed "$sed_pattern")
	fi

	if test $upper -eq 1;
	then
	  newname="$(echo "$el" | tr a-z A-Z)"
	fi

	if test $lower -eq 1;
	then
	  newname="$(echo "$el" | tr A-Z a-z)"
	fi

	if test  "$el" != "$newname";
	then
	  mv "$el" "$newname"
	fi

	if test $recursion -eq 1 -a -d $newname;
	then
	  recursive $newname
	fi

done

