#!/bin/sh

echo "============================= Running Test Script of modify command ==============================="
echo "Creating directory tree ......."

mkdir test
cd test
mkdir directory
mkdir folder
mkdir zoo
touch file1.txt
mkdir directory/first_subdir
touch directory/first_subdir/file_dir
touch directory/sub_file.txt
mkdir directory/hidden_dir
mkdir zoo/lion
touch zoo/lion/zebra
mkdir zoo/tiger
mkdir folder/pictures
mkdir folder/pictures/holiday
touch folder/pictures/holiday/tenerife.jpg
mkdir folder/documents
touch folder/documents/important

ls -R


echo "**************************************** Correct usage examples ************************************"

echo "Running command: ../modify -h"
../modify -h


echo "\n========================================== Running test 1 ============================================="
echo "\nRunning command: ../modify -u zoo directory"
../modify -u zoo directory

echo "\n-----------------Directory tree after test 1--------------------"
ls -R

echo "========================================== End of test 1 ==============================================="


echo "\n========================================== Running test 2 ============================================="
echo "\nRunning command: ../modify -l DIRECTORY"
../modify -l DIRECTORY

echo "\n-----------------Directory tree after test 2--------------------"
ls -R

echo "========================================== End of test 2 ==============================================="


echo "\n========================================== Running test 3 ============================================="
echo "\nRunning command: ../modify -r -u ZOO folder"
../modify -r -u ZOO folder

echo "\n-----------------Directory tree after test 3--------------------"
ls -R

echo "========================================== End of test 3 ==============================================="


echo "\n========================================== Running test 4 ============================================="
echo "\nRunning command: ../modify -r -l FOLDER"
../modify -r -l FOLDER

echo "\n-----------------Directory tree after test 4--------------------"
ls -R

echo "========================================== End of test 4 ==============================================="



echo "\n========================================== Running test 5 ============================================="
echo "\nRunning command: ../modify -r 's/f/EOPSY/' file1.txt folder "
../modify -r 's/f/EOPSY/' file1.txt folder

echo "\n-----------------Directory tree after test 5--------------------"
ls -R

echo "========================================== End of test 5 ==============================================="


echo "\n****************************************Incorrect usage examples ****************************************"


echo "\n========================================== Running test 1 ============================================="
echo "\nRunning command: ../modify -d"
../modify -d

echo "\n========================================== Running test 2 ============================================="
echo "\nRunning command: ../modify -l -u"
../modify -l -u


echo "\n========================================== Running test 3 ============================================="
echo "\nRunning command: ../modify -r 's/[A-Z]/f'"
../modify -r 's/[A-Z]/f'

echo "\n========================================== Running test 4 ============================================="
echo "\nRunning command: ../modify -r -l somefile"
../modify -r -l somefile


echo "================================== End of test script of modify command =================================="

echo "Cleaning test directory......"


cd ..
rm -r test
